
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 06 10:37:40 CST 2014
//----------------------------------------------------

package code;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BITWISE_XOR = 86;
  public static final int AS = 10;
  public static final int INT16_T = 66;
  public static final int PROVIDES = 4;
  public static final int IDENTIFIER = 96;
  public static final int GREATER_EQUAL_THAN = 83;
  public static final int BOOL = 77;
  public static final int TIMES = 21;
  public static final int MESSAGE_T = 74;
  public static final int LESS_THAN = 26;
  public static final int UINT8_T = 62;
  public static final int GREATER_THAN = 27;
  public static final int EXPORT = 69;
  public static final int BITWISE_OR = 30;
  public static final int NAMESPACE = 44;
  public static final int ENUM = 76;
  public static final int CLOSE_CURLY = 15;
  public static final int EXPLICIT = 68;
  public static final int COMMA = 16;
  public static final int VIRTUAL = 50;
  public static final int INT32_T = 67;
  public static final int INT8_T = 65;
  public static final int INTEGER = 87;
  public static final int STRUCT = 75;
  public static final int INTEGER_LITERAL = 97;
  public static final int NOT = 85;
  public static final int FALSE = 37;
  public static final int TASK = 42;
  public static final int WIRES_FROM = 92;
  public static final int BITWISE_NOT = 31;
  public static final int FLOAT = 88;
  public static final int INLINE = 70;
  public static final int GOTO = 81;
  public static final int RESULT_T = 72;
  public static final int CLOSE_BRACE = 95;
  public static final int CLOSE_PAREN = 13;
  public static final int EQCOMPARE = 28;
  public static final int CHARACTER = 90;
  public static final int MOD = 23;
  public static final int PACKET_T = 73;
  public static final int PREPROCESSOR = 94;
  public static final int TRUE = 40;
  public static final int PLUS = 19;
  public static final int DIVIDE = 22;
  public static final int QUESTION = 34;
  public static final int WHILE = 54;
  public static final int IMPLEMENTATION = 7;
  public static final int MODULE = 47;
  public static final int CHAR = 78;
  public static final int INTERFACE = 6;
  public static final int SWITCH = 57;
  public static final int DO = 60;
  public static final int FOR = 53;
  public static final int WIRES_TO = 91;
  public static final int VOID = 80;
  public static final int RETURN = 55;
  public static final int ELSE = 52;
  public static final int BREAK = 56;
  public static final int DOT = 17;
  public static final int INT = 79;
  public static final int EOF = 0;
  public static final int THIS = 39;
  public static final int DEFAULT = 59;
  public static final int OPEN_CURLY = 14;
  public static final int ERROR_T = 71;
  public static final int UINT16_T = 63;
  public static final int POST = 43;
  public static final int MINUS = 20;
  public static final int INCLUDES = 2;
  public static final int OR = 33;
  public static final int error = 1;
  public static final int SEMI_COLON = 11;
  public static final int LESS_EQUAL_THAN = 82;
  public static final int CONTINUE = 61;
  public static final int IF = 51;
  public static final int CONFIGURATION = 3;
  public static final int EQNOT_EQUAL = 84;
  public static final int COLON = 35;
  public static final int TEMPLATE = 49;
  public static final int ATOMIC = 36;
  public static final int USING = 41;
  public static final int COMMAND = 46;
  public static final int OPEN_BRACE = 18;
  public static final int UINT32_T = 64;
  public static final int CASE = 58;
  public static final int OPEN_PAREN = 12;
  public static final int NEW = 38;
  public static final int TYPENAME = 48;
  public static final int STRING = 89;
  public static final int RSHIFT = 25;
  public static final int COMPONENT = 8;
  public static final int AND = 32;
  public static final int LSHIFT = 24;
  public static final int BITWISE_AND = 29;
  public static final int CALL = 98;
  public static final int EVENT = 45;
  public static final int EQUALS = 93;
  public static final int USES = 5;
  public static final int COMPONENTS = 9;
}

